### ISSUE TITLE
No compila en ArchLinux posible error de dependencias

### ISSUE THREAD

**Issue by Tahuri** [centaurialpha/edis#24]
Hola a todos.

    Les comento que en Archlinux no me esta compilando con los ultimos cambios. Les dejo debajo el log que me deja la consola. Saludos

╭─[~/Documentos/ProyectoEdis/edis]─[tahuri@localhost]─[139]─[6123]
╰─[:(] % ./edis
"sni-qt/23393" WARN  17:45:06.449 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
(2, "No existe el fichero o el directorio: 'ctags'")
(2, "No existe el fichero o el directorio: 'ctags'")
Traceback (most recent call last):
  File "/home/tahuri/Documentos/ProyectoEdis/edis/src/ui/contenedores/lateral/arbol_simbolos.py", line 115, in ir_a_linea
    if item.clickeable:
AttributeError: 'QTreeWidgetItem' object has no attribute 'clickeable'
Traceback (most recent call last):
  File "/home/tahuri/Documentos/ProyectoEdis/edis/src/ui/contenedores/lateral/arbol_simbolos.py", line 115, in ir_a_linea
    if item.clickeable:
AttributeError: 'QTreeWidgetItem' object has no attribute 'clickeable'
Traceback (most recent call last):
  File "/home/tahuri/Documentos/ProyectoEdis/edis/src/ui/contenedores/lateral/arbol_simbolos.py", line 115, in ir_a_linea
    if item.clickeable:
AttributeError: 'QTreeWidgetItem' object has no attribute 'clickeable'
False
(2, "No existe el fichero o el directorio: 'ctags'")
(2, "No existe el fichero o el directorio: 'cppcheck'")

**Comment by centaurialpha** [comment]
En la salida del compilador dice algo?
Actualiza el repositorio y por favor prueba de nuevo.
Saludos!
